language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7      
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - cmake
      - cmake-data

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CCC=gcc-5 CCXX=g++-5
    - os: linux
      compiler: clang
      env: CCC=clang-3.7 CCXX=clang++-3.7
        
before_script:
  - export CC=$CCC CXX=$CCXX
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make && ctest
